before:
  hooks:
    - go mod tidy

builds:
  - dir: ./cmd/looking-glass
    env:
      - CGO_ENABLED=0
    flags:
      - -v
    ldflags:
      - -X github.com/simplifi/looking-glass/version.Version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*

checksum:
  name_template: "checksums.txt"

changelog:
  skip: true
