language: go

env:
  - GO111MODULE=on

go:
  - 1.13.x

before_script:
  - go get -u golang.org/x/lint/golint
  - curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh

script:
  - make ci

# Calls goreleaser to build and push artifacts
deploy:
  - provider: script
    skip_cleanup: true
    script: make release
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
